#!/bin/sh
# This is for Starting/Stopping/Restarting Lighttpd. You won't need
# to edit anything.

HOME=/users/home/`whoami`
RAILS_HOME=$HOME/rails/bakagaiku
LIGHTTPD_CONF=$RAILS_HOME/config/lighttpd.conf
PIDFILE=$RAILS_HOME/tmp/lighttpd.pid
export SHELL=/bin/sh

case "$1" in
    start)
      # Starts the lighttpd deamon
	echo "Starting Lighttpd"
	PATH=$PATH:/usr/local/bin /usr/local/sbin/lighttpd -f $LIGHTTPD_CONF
	;;
    stop)
      # stops the daemon bt cat'ing the pidfile
	echo "Stopping Lighttpd"
	kill `/bin/cat $PIDFILE`
	;;
    restart)
      ## Stop the service regardless of whether it was
      ## running or not, start it again.
	echo "Restarting Lighttpd"
	$0 stop
	$0 start
	;;
    reload)
      # reloads the config file by sending HUP
	echo "Reloading config"
	kill -HUP `/bin/cat $PIDFILE`
	;;
    *)
	echo "Usage: lighttpdctrl (start|stop|restart|reload)"
	exit 1
	;;
esac
